### ISSUE TITLE
ImportError: cannot import name 'bda'

### ISSUE THREAD

**Issue by Kincaidr** [ska-sa/xova#26]
I have git cloned and `python setup.py install` the xova software.

When running I get this error:

```
Traceback (most recent call last):
  File "/home/kincaid/venv/bin/xova", line 33, in <module>
    sys.exit(load_entry_point('xova==0.1.1', 'console_scripts', 'xova')())
  File "/home/kincaid/venv/bin/xova", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/kincaid/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 178, in load
    module = import_module(match.group('module'))
  File "/home/kincaid/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kincaid/venv/lib/python3.6/site-packages/xova-0.1.1-py3.6.egg/xova/apps/xova/app.py", line 34, in <module>
    from xova.apps.xova.averaging import (average_main,
  File "/home/kincaid/venv/lib/python3.6/site-packages/xova-0.1.1-py3.6.egg/xova/apps/xova/averaging.py", line 5, in <module>
    from africanus.averaging.dask import (time_and_channel,
ImportError: cannot import name 'bda'
```

**Comment by bennahugo** [comment]
Probably not released in africanus for 3.6. try with 3.8

**Comment by Kincaidr** [comment]
Having trouble creating a 3.8 virtual env on the server, however, I got it to work with python 3.7.
